# Generated by Django 4.0.4 on 2022-04-18 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=250, verbose_name='Название категории')),
                ('category_slug', models.SlugField(blank=True, max_length=250, verbose_name='Слаг поле категории')),
            ],
        ),
        migrations.AddField(
            model_name='mark',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/shop'),
        ),
        migrations.AddField(
            model_name='mark',
            name='mark_slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='Слаг поле марки'),
        ),
        migrations.AddField(
            model_name='model',
            name='model_slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='Слаг поле модели'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='mark_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Название марки'),
        ),
        migrations.AlterField(
            model_name='model',
            name='mark',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='car_shop.mark'),
        ),
        migrations.AlterField(
            model_name='model',
            name='model_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название модели'),
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=255, verbose_name='Оригинальный артикул')),
                ('article_second', models.CharField(max_length=255, verbose_name='Дополнительный артикул')),
                ('part_name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('part_exist', models.BooleanField(verbose_name='Наличие')),
                ('part_price', models.IntegerField(verbose_name='Цена запчасти')),
                ('image', models.ImageField(blank=True, upload_to='images/shop')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='car_shop.category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model', to='car_shop.model'),
        ),
    ]
