# Generated by Django 4.0.4 on 2022-04-18 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_shop', '0002_category_mark_image_mark_mark_slug_model_model_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=250, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(max_length=250, verbose_name='Слаг поле категории'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='mark_name',
            field=models.CharField(max_length=250, verbose_name='Название марки'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='mark_slug',
            field=models.SlugField(max_length=255, verbose_name='Слаг поле марки'),
        ),
        migrations.AlterField(
            model_name='model',
            name='image',
            field=models.ImageField(upload_to='images/shop'),
        ),
        migrations.AlterField(
            model_name='model',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='car_shop.mark'),
        ),
        migrations.AlterField(
            model_name='model',
            name='model_name',
            field=models.CharField(max_length=255, verbose_name='Название модели'),
        ),
        migrations.AlterField(
            model_name='model',
            name='model_slug',
            field=models.SlugField(max_length=255, verbose_name='Слаг поле модели'),
        ),
        migrations.AlterField(
            model_name='part',
            name='image',
            field=models.ImageField(upload_to='images/shop'),
        ),
    ]
