# Generated by Django 4.0.4 on 2022-04-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_shop', '0003_alter_category_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='part_slug',
            field=models.SlugField(blank=True, max_length=250, verbose_name='Слаг'),
        ),
    ]
