# Generated by Django 4.0.4 on 2022-04-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_shop', '0004_part_part_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='part_slug',
            field=models.SlugField(max_length=250, verbose_name='Слаг'),
        ),
    ]
