# Generated by Django 4.0.4 on 2022-04-18 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_shop', '0006_alter_category_table_alter_mark_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='mark',
            options={'verbose_name_plural': 'Марки'},
        ),
        migrations.AlterModelOptions(
            name='model',
            options={'verbose_name_plural': 'Модели'},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'verbose_name_plural': 'Детали'},
        ),
    ]
